### ISSUE TITLE
Meteor 1.3 with new Cordova gives warning

### ISSUE THREAD

**Issue by lucfranken** [mbanting/meteor-cordova-accounts-resume#3]
In Meteor 1.3 Cordova got an update. Now it produces this message:

> WARNING: Attempting to install plugin cordova-plugin-file@3.0.0, but it should have a minimum version of 4.1.1 to ensure compatibility with the current platform versions.
>          Installing the minimum version for convenience, but you should adjust your dependencies.

Related to:

https://github.com/mbanting/meteor-cordova-accounts-resume/blob/master/package.js#L15

It just takes a newer version and works seemingly without issues, only the warning shows up in the console.

**Comment by dpeet** [comment]
@mbanting looks like an easy fix, and I'm having it too!  Just getting some visibility!

**Comment by lesliechw** [comment]
Sorry I haven's setup my own test yet. Just wanted to know, this will continue work even without fix right?

**Comment by lucfranken** [comment]
The message is still there but the plugin seems to work fine.

**Comment by lesliechw** [comment]
@lucfranken, thanks for your reply. Good to know that, at least confirmed a working solution to solve this problem. Have you try fix it by yourself? Any luck?

**Comment by lucfranken** [comment]
Package seems old and unmaintained so I would suggest searching another solution.

**Comment by lesliechw** [comment]
@lucfranken, do you have any other solution yet?

How about fork this package and maintain it?

**Comment by lucfranken** [comment]
You can do that, before you do try contacting the creators of the package maybe there is a reason why it's abandoned.

**Comment by lesliechw** [comment]
Will do, Thanks...

**Comment by mbanting** [comment]
Still here, the package works despite the warning. It's been a busy few months but I'll get a new version out with updated dependencies so that the warning is gone.

**Comment by lucfranken** [comment]
Great thanks @mbanting !

**Comment by mbanting** [comment]
No problem @lucfranken thanks for your patience

**Comment by lesliechw** [comment]
Thanks so much.

**Comment by mbanting** [comment]
Version 1.1.0 released to Atmosphere with updated cordova-plugin-version
